# Generated by Django 4.1 on 2024-11-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_airplane_airport_flight_alter_airplanetype_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticker',
            new_name='Ticket',
        ),
    ]
